### ISSUE TITLE
新纪元

### ISSUE THREAD

**Issue by tomalltruthforyou** [tomalltruthforyou/truth#18]
[![xjy-book](https://cloud.githubusercontent.com/assets/18081243/14840784/d105c716-0c7a-11e6-8687-d9eabda06f17.jpg)](https://github.com/xjy16/xjy/blob/master/README.md)

新紀元週刊，是大紀元新聞集團發行出版的一份全球華人時事週刊。希望能夠對這個世界以新的角度和新的方法進行重新觀察，也以一個新的視野，對東方世界重新認識，以及更加重要的，對我們的內心世界加以省思。

[![xjy548](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy548.jpg)](https://github.com/xjy16/books/blob/master/N548.zip?raw=true)

[![xjy547](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy547.jpg)](https://github.com/xjy16/books/blob/master/N547.zip?raw=true) | [![xjy546](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy546.jpg)](https://github.com/xjy16/books/blob/master/N546.zip?raw=true)
| ------ | ------ |
[![xjy545](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy545.jpg)](https://github.com/xjy16/books/blob/master/N545.zip?raw=true) | [![xjy544](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy544.jpg)](https://github.com/xjy16/books/blob/master/N544.zip?raw=true)
[![xjy543](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy543.jpg)](https://github.com/xjy16/books/blob/master/N543.zip?raw=true) | [![xjy542](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy542.jpg)](https://github.com/xjy16/books/blob/master/N542.zip?raw=true)
[![xjy541](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy541.jpg)](https://github.com/xjy16/books/blob/master/N541.zip?raw=true) | [![xjy540](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy540.jpg)](https://github.com/xjy16/books/blob/master/N540.zip?raw=true)
[![xjy539](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy539.jpg)](https://github.com/xjy16/books/blob/master/N539.zip?raw=true) | [![xjy538](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy538.jpg)](https://github.com/xjy16/books/blob/master/N538.zip?raw=true)
[![xjy537](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy537.jpg)](https://github.com/xjy16/books/blob/master/N537.zip?raw=true) | [![xjy536](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy536.jpg)](https://github.com/xjy16/books/blob/master/N536.zip?raw=true)
[![xjy535](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy535.jpg)](https://github.com/xjy16/books/blob/master/N535.zip?raw=true) | [![xjy534](https://raw.githubusercontent.com/xjy16/books/master/cover/xjy534.jpg)](https://github.com/xjy16/books/blob/master/N534.zip?raw=true)
[![xjy533](https://cloud.githubusercontent.com/assets/18081243/26750681/41ca6aa6-47ee-11e7-9d00-fa85faef291e.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N533.pdf) | [![xjy532](https://cloud.githubusercontent.com/assets/18081243/26338360/002a811e-3f45-11e7-9cea-17a4e712be9c.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N532.pdf)
[![xjy531](https://cloud.githubusercontent.com/assets/18081243/26338359/0028f36c-3f45-11e7-9553-445dabbf5471.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N531.pdf) | [![xjy530](https://cloud.githubusercontent.com/assets/20497750/26086469/ced36e3c-39b8-11e7-9984-018958841119.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N530.pdf)
[![xjy529](https://cloud.githubusercontent.com/assets/20497750/26086468/ced34d94-39b8-11e7-96bb-b4b523cff411.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N529.pdf) | [![xjy528](https://cloud.githubusercontent.com/assets/20497750/26086466/cecf5630-39b8-11e7-9868-6bfc6929394b.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N528.pdf)
[![xjy527](https://cloud.githubusercontent.com/assets/20497750/26086467/ced0e11c-39b8-11e7-9e13-7cf7a1d5c05b.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N527.pdf) | [![xjy526](https://cloud.githubusercontent.com/assets/20497750/25074139/ac0ac572-22ba-11e7-9dbc-2e5b5446d64c.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N526.pdf)
[![xjy525](https://cloud.githubusercontent.com/assets/20497750/25074140/ac2351b4-22ba-11e7-9f60-9d30d64dce14.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N525.pdf) | [![xjy524](https://cloud.githubusercontent.com/assets/18081243/24536199/6b7450e2-159e-11e7-9967-d4f26645de89.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N524.pdf)
| [![xjy523](https://cloud.githubusercontent.com/assets/18081243/24536200/6b8a12ec-159e-11e7-89e1-280890278c12.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N523.pdf) | [![xjy522](https://cloud.githubusercontent.com/assets/18081243/24088563/d6ed9476-0cf9-11e7-86f1-d9d3d99927e6.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N522.pdf) |
[![xjy521](https://cloud.githubusercontent.com/assets/18081243/23782886/34f249ac-051d-11e7-9d8d-86e3c30c706b.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N521.pdf) | [![xjy520](https://cloud.githubusercontent.com/assets/18081243/23782884/32c028f2-051d-11e7-8561-b37746bd07c9.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N520.pdf)
[![xjy519](https://cloud.githubusercontent.com/assets/20497750/23337359/7957c638-fbb0-11e6-9641-964871b315c9.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N519.pdf) | [![xjy518](https://cloud.githubusercontent.com/assets/20497750/23337342/da8df1f8-fbaf-11e6-990b-2867165802a7.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N518.pdf)
[![xjy517](https://cloud.githubusercontent.com/assets/20497750/23337343/dc18dff6-fbaf-11e6-93a0-7e4d1c0afbb6.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N517.pdf) | [![xjy516](https://cloud.githubusercontent.com/assets/18081243/22404323/2875ec26-e5f4-11e6-8e8b-0d2e2004e613.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N516.pdf)
[![xjy515](https://cloud.githubusercontent.com/assets/18081243/22190180/122eb432-e0e7-11e6-9d04-95866c01192d.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N515.pdf) | [![xjy514](https://cloud.githubusercontent.com/assets/18081243/21970497/8f7d22dc-db6c-11e6-99c7-7965739d801f.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N514.pdf)
[![xjy513](https://cloud.githubusercontent.com/assets/18081243/21791019/0a02dbe6-d6ae-11e6-9572-a2464c97d22b.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N513.pdf)|[![xjy512](https://cloud.githubusercontent.com/assets/18081243/21574968/d93c326a-cef5-11e6-8897-553eea840762.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N512.pdf)|[![xjy511](https://cloud.githubusercontent.com/assets/18081243/21574966/d658be92-cef5-11e6-8f77-62c615787d45.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N511.pdf) 
[![xjy510](https://cloud.githubusercontent.com/assets/18081243/21172084/ca46dfd4-c1c7-11e6-930b-1cd612983e77.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N510.pdf) | [![xjy509](https://cloud.githubusercontent.com/assets/18081243/21172081/c7915d28-c1c7-11e6-9188-a2b4c2f5cdc5.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N509.pdf) | [![xjy508](https://cloud.githubusercontent.com/assets/18081243/21172078/c4b453bc-c1c7-11e6-960e-a9483cabf1e8.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N508.pdf) 
[![xjy507](https://cloud.githubusercontent.com/assets/18081243/20588884/7cfe864e-b210-11e6-9aaa-50df4150034e.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N507.pdf) | [![xjy506](https://cloud.githubusercontent.com/assets/18081243/20588879/791f4acc-b210-11e6-8467-86b7a2977de7.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N506.pdf) | [![xjy505](https://cloud.githubusercontent.com/assets/18081243/20588873/72ad2dda-b210-11e6-84a4-aedbed7c8bb3.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N505.pdf) 
[![xjy504](https://cloud.githubusercontent.com/assets/18081243/19881797/9dbd0508-a000-11e6-9635-21783a12cf37.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N504.pdf) |  [![xjy503](https://cloud.githubusercontent.com/assets/18081243/19881792/9a22a6a0-a000-11e6-9b25-3f9ed4310bde.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N503.pdf) | [![xjy502](https://cloud.githubusercontent.com/assets/18081243/19881789/94b6967c-a000-11e6-99e4-fe89bf88edab.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N502.pdf) 
[![xjy501](https://cloud.githubusercontent.com/assets/18081243/19426372/71abd6fa-942b-11e6-8f4b-ef9c57bb42d6.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N501.pdf) | [![xjy500](https://cloud.githubusercontent.com/assets/18081243/19227594/9beb5ac4-8eab-11e6-8e7d-61590baadba1.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N500.pdf) | [![xjy499](https://cloud.githubusercontent.com/assets/18081243/18942119/0c9fd2a8-8606-11e6-877e-6a89cd6f441e.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N499.pdf) 
[![xjy498](https://cloud.githubusercontent.com/assets/18081243/18942116/09e95610-8606-11e6-8f60-af4b38743c45.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N498.pdf) | [![xjy497](https://cloud.githubusercontent.com/assets/18081243/18942115/071988a6-8606-11e6-8802-3e365442d9b7.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N497.pdf) | [![xjy496](https://cloud.githubusercontent.com/assets/18081243/18397467/e4516b84-76b7-11e6-9fc4-a125c974c162.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N496.pdf) 
[![xjy495](https://cloud.githubusercontent.com/assets/18081243/18397465/e17e6a60-76b7-11e6-8170-11fde29c468d.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N495.pdf) | [![xjy494](https://cloud.githubusercontent.com/assets/18081243/17914450/cf6afb78-6991-11e6-8662-1a73da7c8dab.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N494.pdf) | [![xjy493](https://cloud.githubusercontent.com/assets/18081243/17914447/cbf4e2d8-6991-11e6-842d-142ccaba912d.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N493.pdf) 
[![xjy492](https://cloud.githubusercontent.com/assets/18081243/17645462/48dd1de6-6196-11e6-8540-e047fe92d0c5.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N492.pdf) | [![xjy491](https://cloud.githubusercontent.com/assets/18081243/17471322/de01d9c4-5d32-11e6-84fa-7c882463fff2.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N491.pdf) | [![xjy490](https://cloud.githubusercontent.com/assets/18081243/17471329/e6c25ca0-5d32-11e6-9b2a-47d75e433200.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N490.pdf) 
[![xjy489](https://cloud.githubusercontent.com/assets/18081243/17471326/e191faba-5d32-11e6-8541-d0a324617f69.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N489.pdf) | [![xjy488](https://cloud.githubusercontent.com/assets/18081243/17000644/f17aa5c8-4eb2-11e6-89a3-829fec5d71d5.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N488.pdf) | [![xjy487](https://cloud.githubusercontent.com/assets/18081243/16736778/fb0e0ef4-477d-11e6-871c-7b27c031e3cf.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N487.pdf) 
[![xjy486](https://cloud.githubusercontent.com/assets/18081243/16736775/f809a362-477d-11e6-8c9c-2f4aaf41fd59.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N486.pdf) | [![xjy485](https://cloud.githubusercontent.com/assets/18081243/16354918/700717c2-3a96-11e6-9e57-6082d7a6e34a.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N485.pdf) | [![xjy484](https://cloud.githubusercontent.com/assets/18081243/16131845/004e44ba-3400-11e6-90a8-0a89818bd297.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N484.pdf) 
[![xjy483](https://cloud.githubusercontent.com/assets/18081243/16016092/931d11c4-3188-11e6-93c6-e5187e7ec007.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N483.pdf) | [![xjy482](https://cloud.githubusercontent.com/assets/18081243/15790337/58aac754-29c0-11e6-8c94-5a4c49acc897.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N482.pdf) | [![xjy481](https://cloud.githubusercontent.com/assets/18081243/15528385/0c0f396e-2233-11e6-9a7a-1bc346c2cf22.jpg)](https://d1br6nm36173c9.cloudfront.net/pdf/xjyzk/N481.pdf)

**Comment by whyas** [comment]
很黄很暴力

**Comment by tomalltruthforyou** [comment]
沒有真正閱讀吧？

**Comment by whyas** [comment]
你这是在害我，这样不好的。会出事

**Comment by tomalltruthforyou** [comment]
新紀元週刊，是大紀元新聞集團發行出版的一份全球華人時事週刊。希望能夠對這個世界以新的角度和新的方法進行重新觀察，也以一個新的視野，對東方世界重新認識，以及更加重要的，對我們的內心世界加以省思。
